name: characters
version: 1.1.1-dev
description: String replacement with operations that are Unicode/grapheme cluster aware.
repository: https://www.github.com/dart-lang/characters

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0
  lints: ^1.0.0
