name: characters
version: 1.1.0-nullsafety.5
description: String replacement with operations that are Unicode/grapheme cluster aware.
homepage: https://www.github.com/dart-lang/characters

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety
  pedantic: ^1.10.0-nullsafety
